[project]
name = "aided-chess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["dill>=0.3.9", "scikit-learn>=1.6.1", "ultralytics>=8.3.91"]
